<?php 
/**
	Admin Page Framework v3.7.11 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/yucca-shop>
	Copyright (c) 2013-2016, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class yucca_shopAdminPageFramework_Property_taxonomy_field extends yucca_shopAdminPageFramework_Property_post_meta_box {
    public $_sPropertyType = 'taxonomy_field';
    public $aTaxonomySlugs;
    public $sOptionKey;
}
